//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Actors
    {
        public int Id { get; set; }
        public int Actor_Id { get; set; }
        public int Movie_Id { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
